### ISSUE TITLE
Is Garnet production ready? 

### ISSUE THREAD

**Issue by dceravigupta** [microsoft/garnet#114]
Congrats on the release of this awesome project. 

Given the project came out of Microsoft Research team, wondering is it ready to use in production?

Primarily, I wanted to know whether it is already being used in some form in production within Microsoft?

**Comment by Anakin100100** [comment]
It looks like it's been for several months based on https://github.com/microsoft/garnet/issues/38#issuecomment-2010672677

**Comment by badrishc** [comment]
Garnet has been used in production for more than a year in various internal cache scenarios at Microsoft. I am not talking about small use cases here, rather, these are large-scale scenarios with extremely large operation volumes, stringent constraints on 99.9th percentile latency goals, and heavy requirements on long-term stability. Garnet usually runs over distributed platforms such as Service Fabric (Windows) and Kubernetes (Linux). It has been running in these deployments for many months.

We are not able to provide more details in public at this point, but we hope to work with our partners to put out future blog posts and articles on their use cases and experiences. See our blog post for [more details](https://www.microsoft.com/en-us/research/blog/introducing-garnet-an-open-source-next-generation-faster-cache-store-for-accelerating-applications-and-services/) as well.

Since you are at Microsoft, please reach out to us and we can discuss more. Thanks!
