### ISSUE TITLE
CLUSTERDOWN for read  - Replica stuck in recovery 

### ISSUE THREAD

**Issue by msft-paddy14** [microsoft/garnet#226]
Replicas are marked as recovering after they receive `CLUSTER REPLICATE` and before they attach to primary to snapshot. However, if primary is down and sync is requested, replica will reset it's state but not recovery flag. If it's assigned as primary later, it will accept writes but not reads and report CLUSTERDOWN as per https://github.com/microsoft/garnet/blob/main/libs/cluster/Session/ClusterSlotVerify.cs#L33

``` txt
Repro:
1. Start N1 primary and replica N2. 
2. Issue `CLUSTER REPLICATE`<node id of N1> to N2. (N2 transitions to secondary state)
3. Kill N1 (there might be a race and this needs to happen quickly)
4. N2 will revert to unassigned state if N1 fails initial checkpoint request but is stuck in recovery state.
5. Assign N2 as primary with some slots
6.  Send read request to N2
7. CLUSTERDOWN reported
```

Though a node can still be stuck in recovery after this stage - it will atleast transition to secondary if this step completes. As a result, we can take corrective action  - ideally good idea would be to expose metric like Redis's  `master_sync_last_io_seconds_ago` so admin can take corrective action.

**Comment by vazois** [comment]
Great catch! I think there are two issues here, one is the replica remains in recovering state when CLUSTER REPLICATE fails, and the other is how do we expose metrics related to syncing on the replica side including **master_sync_last_io_seconds_ago**.
The first should be fairly easy to correct. I will provide some context below if you want to take a stab at it.

**Fixing the stuck in recovering state bug**
The **ReplicaReceiveCheckpoint.cs** contains all the operations executed from the replica side to complete syncing with the primary. **InitiateReplicaSync** is where we wait for the primary to complete sending the checkpoint and if that fails because connection is interrupted then we will reset the role of the local node back to primary. There I think we should be resetting the ***recovering*** variable back to false. We might need to check up the call stack to see if any other points of failure might end up resulting in the same race condition.

**Exposing metrics**
For the second part, we might to keep track of a collection of metrics related to replication. That will require some refactoring of the current replication code from the replica side. I imagine we should have a ReplicateSession that contains the related operations under ReplicaReceiveCheckpoint.cs and also a struct with all the associated metrics for that ReplicateSession.

Below are all the associated metrics. Do you have any specific requirements, or we just need to add the one metric mentioned above?

- master_sync_total_bytes: Total number of bytes that need to be transferred. this may be 0 when the size is unknown (for example, when the repl-diskless-sync configuration directive is used)
- master_sync_read_bytes: Number of bytes already transferred
- master_sync_left_bytes: Number of bytes left before syncing is complete (may be negative when master_sync_total_bytes is 0)
- master_sync_perc: The percentage master_sync_read_bytes from master_sync_total_bytes, or an approximation that uses loading_rdb_used_mem when master_sync_total_bytes is 0
- master_sync_last_io_seconds_ago: Number of seconds since last transfer I/O during a SYNC operation
