### ISSUE TITLE
Commands allowed on subscribe session

### ISSUE THREAD

**Issue by ncoonrod** [microsoft/garnet#437]
### Describe the bug

I'm using the Redis client on Node.js v18.20.3 with the docker image ghcr.io/microsoft/garnet:1

When I accidentally use pub and sub on the same client, the client crashes and I get the error: SocketClosedUnexpectedlyError: Socket closed unexpectedly

Doing the same stupid thing, using the docker image Redis:7.2 I get:
ErrorReply: ERR Can't execute 'publish': only (P|S)SUBSCRIBE / (P|S)UNSUBSCRIBE / PING / QUIT / RESET are allowed in this context

This is the correct functionality, however I think it could use a better error message.

### Steps to reproduce the bug

Use pub/sub on the same client and try to publish a message. The client will crash with the error: SocketClosedUnexpectedlyError: Socket closed unexpectedly

Again, functionality is expected, just hoping to get a better error message.

### OS version

Ubuntu 22.04 Linux x64

**Comment by badrishc** [comment]
This was a conscious decision we made to allow user commands on the subscribe session, even in RESP2, just because the system is designed to handle that easily, so why spend clock cycles detecting that we are in a subscribe session and preventing it. Open to changing this design decision if everyone feels we should.
