### ISSUE TITLE
Remove support for dotnet 6

### ISSUE THREAD

**Issue by Meir017** [microsoft/garnet#578]
### Feature request type

enhancement

### Is your feature request related to a problem? Please describe

dotnet 6 will reach end-of-life by Nov 12, 2024 (see https://learn.microsoft.com/en-us/lifecycle/products/microsoft-net-and-net-core)

### Describe the solution you'd like

support only the latest LTS version of dotnet

### Additional context

this blocks #379

**Comment by akoken** [comment]
I don’t understand why .NET 6 support is being removed, especially since it’s an LTS version with time remaining before it’s out of support. For many companies, switching between .NET versions isn’t as straightforward in practice.

If there is an API diff, [preprocessor directives](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives) can be used.

Additionally, I wouldn’t recommend adding .NET 9 support before its final release. You could end up questioning whether a bug is in Garnet or .NET 9.

**Comment by badrishc** [comment]
If there are any open source users of Garnet who are still on .NET 6, please let us know.
