### ISSUE TITLE
The `PX` command does not seem to be supported

### ISSUE THREAD

**Issue by yzy613** [microsoft/garnet#62]
Hi,
The `PX` command does not seem to be supported.

Garnet reports `ERR unknown command` when I am using `SET k1 v1 PX 10000`.

**Comment by badrishc** [comment]
Correct, this was not added due to lack of interest in the past. Should be an easy extension to the existing SET logic. Contributions welcome!

Basic idea:

* Edit `NetworkSETEXNX` in https://github.com/microsoft/garnet/blob/main/libs/server/Resp/BasicCommands.cs
* Add an `if` for [PX] similar to [EX]  at https://github.com/microsoft/garnet/blob/main/libs/server/Resp/BasicCommands.cs#L470
* Set a bool highPrecision to `true` if [PX] is specified
* Take `highPrecision` as argument to `NetworkSET_EX` and `NetworkSET_Conditional`
* Change https://github.com/microsoft/garnet/blob/main/libs/server/Resp/BasicCommands.cs#L612 to handle `highPrecision` -- something like:
  `SpanByte.Reinterpret(inputPtr).ExtraMetadata = DateTimeOffset.UtcNow.Ticks + (highPrecision ? TimeSpan.FromMilliseconds(expiry).Ticks : TimeSpan.FromSeconds(expiry).Ticks)`.
