### ISSUE TITLE
Update docker ubuntu images to use noble instead of jammy

### ISSUE THREAD

**Issue by Meir017** [microsoft/garnet#627]
### Feature request type

enhancement

### Is your feature request related to a problem? Please describe

Garnet uses the `jammy` tags (Ubuntu 22.04), we should upgrade to use the latest LTS with the tag `noble`

### Describe the solution you'd like

modify `Dockerfile.chiseled` & `Dockerfile.ubuntu` to use the new `noble` tag

### Additional context

see 
- https://github.com/dotnet/dotnet-docker/blob/main/documentation/ubuntu-chiseled.md
- https://mcr.microsoft.com/en-us/product/dotnet/runtime/about
- https://mcr.microsoft.com/en-us/product/dotnet/sdk/about

**Comment by akoken** [comment]
What is the benefit of making this change? Ubuntu Jammy is already an [LTS](https://ubuntu.com/about/release-cycle) version, and a higher version does not always guarantee improved stability and performance. In a container environment, upgrading the OS version has less impact than upgrading the .NET version. Additionally, we have encountered some performance issues with Noble in some of our customers’ setups and have filed an issue in Ubuntu Launchpad that still remains open.

If an update is decided upon, please create an additional Dockerfile for Noble instead of modifying the existing ones.)
