### ISSUE TITLE
"databases" misreported

### ISSUE THREAD

**Issue by mgravell** [microsoft/garnet#775]
### Describe the bug

The following is unexpected:

``` txt
> config get databases
* 2
 [0]$ databases
 [1]$ 16
> select 1
- ERR invalid database index.
```

If `select` isn't fully implemented, `databases` should probably report `1`. Reporting 16 but erroring if trying to change the database is... weird.

### Steps to reproduce the bug

`select 1` (or anything else greater than zero and less than the reported `databases`)

note that `select 0` works fine and as expected

I *suspect* the real "bug" here is in `config get`, in particular `databases`

**Comment by Vijay-Nirmal** [comment]
Looks like if the cluster mode is enabled `config get databases` return as `16` else `1`. Since Garnet doesn't support multiple database (#61), I think we should always return `1` 

https://github.com/microsoft/garnet/blob/9230a4494ae3439196b811e01071b176f7d942e1/libs/server/ServerConfig.cs#L83

**Comment by vazois** [comment]
For cluster mode, I think right now we are on par with Redis. We are basically returning the following. I guess the only difference is that Redis executes successfully for SELECT 0, so that might need to be fixed. 
![Image](https://github.com/user-attachments/assets/943f680f-c65d-43b2-8bac-7ec22b9dd6df)

For the standalone, I guess it makes sense to advertise databases = 1. I am not sure though if there is any expectation from the clients to observe a value of 16. @mgravell, is there such thing? If not, then should be fine to return databases = 1.
Let me know if you are going to create a PR for this or else I can do it. It should be simple fix.

**Comment by rnz** [comment]
May be better implement namespacing - https://github.com/microsoft/garnet/issues/415 ?

**Comment by mgravell** [comment]
Re select 0: from memory (not at PC), that already worked fine

Re Redis; I'll check what they return, good point; if they also return 16,
then: it is equally misleading, and "check the cluster mode first, before
even considering the databases setting" is totally valid.

**Comment by vazois** [comment]
> [@vazois](https://github.com/vazois) May be better implement namespacing - [#415](https://github.com/microsoft/garnet/issues/415) ?
> 
> Also redis support not only 16 databases, this parameter can be configured https://github.com/valkey-io/valkey/blob/45d596e1216472e49b9f950a4b9a040b6e87add6/valkey.conf#L396C1-L396C13

We do not have plans to support namespaces. Our initial assessment is that it will be detrimental to performance. An alternative to namespaces (if that is the functionality you are looking for) could be using the ACL functionality to add permissions based on key pattern. Though this could also potentially be detrimental to performance.

**Comment by vazois** [comment]
I have posted PR #800 to fix the above issue. @mgravell let me know if you have any issues with the proposed fix.
